"""
This type stub file was generated by pyright.
"""

"""
Getting and saving bing image search results.
"""
bp = ...
@bp.route("/search/<int:langid>/<string:text>/<string:searchstring>", methods=["GET"])
def bing_search(langid, text, searchstring): # -> str:
    "Do an image search."
    ...

@bp.route("/save", methods=["POST"])
def bing_save(): # -> Response:
    """
    Save the posted image data to DATAPATH/userimages,
    returning the filename.
    """
    ...

@bp.route("/manual_image_post", methods=["POST"])
def manual_image_post(): # -> Response:
    """
    For manual posts of images (not bing image clicks).
    Save the posted image data to DATAPATH/userimages,
    returning the filename.
    """
    ...

