"""
This type stub file was generated by pyright.
"""

from .migrator import SqliteMigrator

"""
Database setup:

- Creates database if necessary.
- Runs migrations.
- Manages backups pre-migration.

Methods:

- setup_db(app_config): setup a db with the given config.
"""
class BackupManager:
    """
    Creates db backups when needed, prunes old backups.
    """
    def __init__(self, file_to_backup, backup_directory, max_number_of_backups) -> None:
        ...
    
    def do_backup(self, next_backup_datetime=...): # -> None:
        """
        Perform the db file backup to backup_dir,
        pruning old backups.
        """
        ...
    


class Setup:
    """
    Main setup class, coordinates other classes.
    """
    def __init__(self, db_filename: str, baseline_schema_file: str, backup_manager: BackupManager, migrator: SqliteMigrator, output_func=...) -> None:
        ...
    
    def setup(self): # -> None:
        """
        Do database setup, making backup if necessary, running migrations.
        """
        ...
    


def setup_db(app_config, output_func=...): # -> None:
    """
    Main setup routine.
    """
    ...

