"""
This type stub file was generated by pyright.
"""

"""
Database migration manager.

Runs migrations and logs them to a _migrations table so they aren't
run twice.  Runs repeatable migrations always.
"""
class SqliteMigrator:
    """
    Sqlite migrator class.

    Follows the principles documented in
    https://github.com/jzohrab/DbMigrator/blob/master/docs/managing_database_changes.md
    """
    def __init__(self, location, repeatable) -> None:
        ...
    
    def has_migrations(self, conn): # -> bool:
        """
        Return True if have non-applied migrations.
        """
        ...
    
    def do_migration(self, conn): # -> None:
        """
        Run all migrations, then all repeatable migrations.
        """
        ...
    


