"""
This type stub file was generated by pyright.
"""

"""
Reading rendering helpers.
"""
def find_all_Terms_in_string(s, language): # -> List[Term]:
    """
    Find all terms contained in the string s.

    For example
    - given s = "Here is a cat"
    - given terms in the db: [ "cat", "a cat", "dog" ]

    This would return the terms "cat" and "a cat".
    """
    ...

class RenderableSentence:
    """
    A collection of TextItems to be rendered.
    """
    def __init__(self, sentence_id, textitems) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    


def get_paragraphs(s, language): # -> list:
    """
    Get array of arrays of RenderableSentences for the given string s.
    """
    ...

