"""
This type stub file was generated by pyright.
"""

"""
/language endpoints.
"""
bp = ...
@bp.route("/index")
def index(): # -> str:
    """
    List all languages, with book and term counts.
    """
    ...

@bp.route("/edit/<int:langid>", methods=["GET", "POST"])
def edit(langid): # -> Response | str:
    """
    Edit a language.
    """
    ...

@bp.route("/new", defaults={ "langname": None }, methods=["GET", "POST"])
@bp.route("/new/<string:langname>", methods=["GET", "POST"])
def new(langname): # -> Response | str:
    """
    Create a new language.
    """
    ...

@bp.route("/delete/<int:langid>", methods=["POST"])
def delete(langid): # -> Response:
    """
    Delete a language.
    """
    ...

@bp.route("/list_predefined", methods=["GET"])
def list_predefined(): # -> str:
    "Show predefined languages that are not already in the db."
    ...

@bp.route("/load_predefined/<langname>", methods=["GET"])
def load_predefined(langname): # -> Response:
    "Load a predefined language and its stories."
    ...

