"""
This type stub file was generated by pyright.
"""

"Language helper methods."
def get_supported_defs(): # -> list:
    "Return supported language definitions."
    ...

def predefined_languages(): # -> list:
    "Languages defined in yaml files."
    ...

def get_language_def(lang_name):
    "Get a lang def and its stories."
    ...

def load_language_def(lang_name):
    "Load a language def and its stories, save to database."
    ...

