"""
This type stub file was generated by pyright.
"""

from typing import List
from lute.parse.base import AbstractParser, ParsedToken

"""
Parsing for single-character languages.

The parser uses some Language settings (e.g., word characters) to
perform the actual parsing.

Includes classes:

- ClassicalChineseParser

"""
class ClassicalChineseParser(AbstractParser):
    """
    A general parser for space-delimited languages,
    such as English, French, Spanish ... etc.
    """
    @classmethod
    def name(cls): # -> Literal['Classical Chinese']:
        ...
    
    def get_parsed_tokens(self, text: str, language) -> List[ParsedToken]:
        """
        Returns ParsedToken array for given language.
        """
        ...
    


