"""
This type stub file was generated by pyright.
"""

from lute.parse.base import AbstractParser

"""
Parser registry.

List of available parsers.
"""
__LUTE_PARSERS__ = ...
def init_parser_plugins(): # -> None:
    """
    Initialize parsers from plugins
    """
    ...

def get_parser(parser_name) -> AbstractParser:
    "Return the supported parser with the given name."
    ...

def is_supported(parser_name) -> bool:
    "Return True if the specified parser is present and supported."
    ...

def supported_parsers(): # -> list[tuple[str, Any]]:
    """
    List of supported parser strings and classes.
    """
    ...

def supported_parser_types(): # -> list[str]:
    """
    List of supported Language.parser_types
    """
    ...

