"""
This type stub file was generated by pyright.
"""

from flask_wtf import FlaskForm

"""
Forms while reading.
"""
class TextForm(FlaskForm):
    """
    Text page - for editing a page.
    """
    text = ...


