"""
This type stub file was generated by pyright.
"""

"""
/read endpoints.
"""
bp = ...
@bp.route("/<int:bookid>", methods=["GET"])
def read(bookid): # -> Response | str:
    """
    Read a book, opening to its current page.

    This is called from the book listing, on Lute index.
    """
    ...

@bp.route("/<int:bookid>/page/<int:pagenum>", methods=["GET"])
def read_page(bookid, pagenum): # -> Response | str:
    """
    Read a particular page of a book.

    Called from term Sentences link.
    """
    ...

@bp.route("/page_done", methods=["post"])
def page_done(): # -> Response:
    "Handle POST when page is done."
    ...

@bp.route("/delete_page/<int:bookid>/<int:pagenum>", methods=["GET"])
def delete_page(bookid, pagenum): # -> Response:
    """
    Delete page.
    """
    ...

@bp.route("/new_page/<int:bookid>/<position>/<int:pagenum>", methods=["GET", "POST"])
def new_page(bookid, position, pagenum): # -> Response | str:
    "Create a new page."
    ...

@bp.route("/save_player_data", methods=["post"])
def save_player_data(): # -> Response:
    "Save current player position, bookmarks.  Called on a loop by the player."
    ...

@bp.route("/renderpage/<int:bookid>/<int:pagenum>", methods=["GET"])
def render_page(bookid, pagenum): # -> Response | str:
    "Method called by ajax, render the given page."
    ...

@bp.route("/empty", methods=["GET"])
def empty(): # -> Literal['']:
    "Show an empty/blank page."
    ...

@bp.route("/termform/<int:langid>/<text>", methods=["GET", "POST"])
def term_form(langid, text): # -> str:
    """
    Create a multiword term.
    """
    ...

@bp.route("/edit_term/<int:term_id>", methods=["GET", "POST"])
def edit_term_form(term_id): # -> str:
    """
    Edit a term.
    """
    ...

@bp.route("/termpopup/<int:termid>", methods=["GET"])
def term_popup(termid): # -> str:
    """
    Show a term popup for the given DBTerm.
    """
    ...

@bp.route("/flashcopied", methods=["GET"])
def flashcopied(): # -> str:
    ...

@bp.route("/editpage/<int:bookid>/<int:pagenum>", methods=["GET", "POST"])
def edit_page(bookid, pagenum): # -> Response | str:
    "Edit the text on a page."
    ...

