"""
This type stub file was generated by pyright.
"""

import click

"""
Simple CLI commands.
"""
bp = ...
@bp.cli.command("hello")
def hello(): # -> None:
    "Say hello -- proof-of-concept CLI command only."
    ...

@bp.cli.command("language_export")
@click.argument("language")
@click.argument("output_path")
def language_export(language, output_path): # -> None:
    """
    Get all terms from all books in the language, and write a
    data file of term frequencies and children.
    """
    ...

@bp.cli.command("book_term_export")
@click.argument("bookid")
@click.argument("output_path")
def book_term_export(bookid, output_path): # -> None:
    """
    Get all terms for the given book, and write a
    data file of term frequencies and children.
    """
    ...

