"""
This type stub file was generated by pyright.
"""

"""
Generate a rough data file for a given language for all terms.

Gets *all* books for a given language, and writes a data file to
the specified csv output file name.

Generates csv with headings:
term; count; familycount; books; definition; status; children

e.g.
term; count; familycount; books; definition; status; children
haber; 100; 1500; book1,book2; to exist; 99; hay (500), he (200), has (150) ...
"""
def generate_language_file(language_name, outfile_name): # -> None:
    """
    Generate the datafile for the language.
    """
    ...

def generate_book_file(bookid, outfile_name): # -> None:
    """
    Generate the datafile for the book.
    """
    ...

