"""
This type stub file was generated by pyright.
"""

"""
/stats endpoints.
"""
bp = ...
@bp.route("/")
def index(): # -> str:
    "Main page."
    ...

@bp.route("/data")
def get_data(): # -> Response:
    "Ajax call."
    ...

