"""
This type stub file was generated by pyright.
"""

"""
Calculating stats.
"""
def get_chart_data(): # -> dict:
    "Get data for chart for each language."
    ...

def get_table_data(): # -> list:
    "Wordcounts by lang in time intervals."
    ...

