"""
This type stub file was generated by pyright.
"""

"""
Factory.

Methods: create_app.
"""
def create_app(app_config_path=..., extra_config=..., output_func=...): # -> Flask:
    """
    App factory.  Calls dbsetup, and returns Flask app.

    Args:
    - app_config_path: path to yml file.  If None, use root config or default.
    - extra_config: dict, e.g. pass { 'TESTING': True } during unit tests.
    """
    ...

