"""
This type stub file was generated by pyright.
"""

"""
User entry point.

Start lute running on given port, or 5000 if not set.

e.g.

python -m lute.main --port 5001
"""
if __name__ == "__main__":
    parser = ...
