"""
This type stub file was generated by pyright.
"""

from flask_wtf import FlaskForm

"""
Term import.
"""
bp = ...
class TermImportForm(FlaskForm):
    "Form for imports."
    text_file = ...
    create_terms = ...
    new_as_unknown = ...
    update_terms = ...


@bp.route("/index", methods=["GET", "POST"])
def term_import_index(): # -> Response | str:
    "Import posted file."
    ...

