"""
This type stub file was generated by pyright.
"""

"""
Term import.
"""
class BadImportFileError(Exception):
    """
    Raised if the import file is bad:

    - unknown language or status
    - dup term
    etc.
    """
    ...


def import_file(filename, create_terms=..., update_terms=..., new_as_unknowns=...): # -> dict[str, int]:
    """
    Validate and import file.

    Throws BadImportFileError if file contains invalid data.
    """
    ...

