"""
This type stub file was generated by pyright.
"""

"""
Show bookmarks in datatables.
"""
def get_data_tables_list(parameters, book_id): # -> dict[str, Any]:
    "Bookmark json data for datatables."
    ...

