"""
This type stub file was generated by pyright.
"""

"""
/bookmarks endpoint
"""
bp = ...
@bp.route("/<int:bookid>/datatables", methods=["POST"])
def datatables_bookmarks(bookid): # -> Response:
    "Get datatables json for bookmarks."
    ...

@bp.route("/<int:bookid>", methods=["GET"])
def bookmarks(bookid): # -> str:
    "Get all bookarks for given bookid."
    ...

@bp.route("/add", methods=["POST"])
def add_bookmark(): # -> Response:
    "Add bookmark"
    ...

@bp.route("/delete", methods=["POST"])
def delete_bookmark(): # -> Response:
    "Delete bookmark"
    ...

@bp.route("/edit", methods=["POST"])
def edit_bookmark(): # -> Response:
    "Edit bookmark"
    ...

