"""
This type stub file was generated by pyright.
"""

"""
App configuration.
"""
class AppConfig:
    """
    Configuration wrapper around yaml file.

    Adds various properties for lint-time checking.
    """
    def __init__(self, config_file_path) -> None:
        """
        Load the required configuration file.
        """
        ...
    
    @property
    def sqliteconnstring(self): # -> str:
        "Full sqlite connection string."
        ...
    
    @staticmethod
    def configdir(): # -> str:
        "Return the path to the configuration file directory."
        ...
    
    @staticmethod
    def default_config_filename(): # -> str:
        "Return the path to the default configuration file."
        ...
    


