"""
This type stub file was generated by pyright.
"""

"""
Data cleanup routines.

Sometimes required as data management changes.
These cleanup routines will be called by the app_factory.
"""
def clean_data(): # -> None:
    "Clean all data as required."
    ...

