"""
This type stub file was generated by pyright.
"""

"""
Functions to manage demo database.

Lute db comes pre-loaded with some demo data.  User can view Tutorial,
wipe data, etc.

The db settings table contains a record, StKey = 'IsDemoData', if the
data is demo.
"""
def contains_demo_data(): # -> bool:
    """
    True if IsDemoData setting is present.
    """
    ...

def remove_flag(): # -> None:
    """
    Remove IsDemoData setting.
    """
    ...

def tutorial_book_id(): # -> int | None:
    """
    Return the book id of the tutorial.
    """
    ...

def delete_demo_data(): # -> None:
    """
    If this is a demo, wipe everything.
    """
    ...

def load_demo_languages(): # -> None:
    """
    Load selected predefined languages.  Assume everything is supported.

    This method will also be called during acceptance tests, so it's public.
    """
    ...

def load_demo_stories(): # -> None:
    "Load the stories."
    ...

def load_demo_data(): # -> None:
    """
    Load the data.
    """
    ...

