"""
This type stub file was generated by pyright.
"""

"""
Db management.
"""
def delete_all_data(): # -> None:
    """
    DANGEROUS!  Delete everything, restore user settings, clear sys settings.

    NO CHECKS ARE PERFORMED.
    """
    ...

