"""
This type stub file was generated by pyright.
"""

"""
Backup routes.

Backup settings form management, and running backups.
"""
bp = ...
@bp.route("/index")
def index(): # -> str:
    """
    List all backups.
    """
    ...

@bp.route("/download/<filename>")
def download_backup(filename): # -> Response:
    "Download the given backup file."
    ...

@bp.route("/backup", methods=["GET"])
def backup(): # -> str:
    """
    Endpoint called from front page.

    With extra arg 'type' for manual.
    """
    ...

@bp.route("/do_backup", methods=["POST"])
def do_backup(): # -> Response | tuple[Response, Literal[500]]:
    """
    Ajax endpoint called from backup.html.
    """
    ...

@bp.route("/skip_this_backup", methods=["GET"])
def handle_skip_this_backup(): # -> Response:
    "Update last backup date so backup not attempted again."
    ...

