"""
This type stub file was generated by pyright.
"""

import os
from datetime import datetime
from typing import List, Union

"""
Db and image backup.
"""
class BackupException(Exception):
    """
    Raised if export bombs for some reason.
    """
    ...


class DatabaseBackupFile:
    """
    A representation of a lute backup file to hold metadata attributes.
    """
    def __init__(self, filepath: Union[str, os.PathLike]) -> None:
        ...
    
    def __lt__(self, other) -> bool:
        ...
    
    @property
    def last_modified(self) -> datetime:
        ...
    
    @property
    def size_bytes(self) -> int:
        ...
    
    @property
    def size(self) -> str:
        """
        A human-readable string representation of the size of the file.

        Eg.
        1746 bytes
        4 kB
        27 MB
        """
        ...
    


def create_backup(app_config, settings, is_manual=..., suffix=...): # -> str:
    """
    Create backup using current app config, settings.

    is_manual is True if this is a user-triggered manual
    backup, otherwise is False.

    suffix can be specified for test.

    settings are from Setting.get_backup_settings().
      - backup_enabled
      - backup_dir
      - backup_auto
      - backup_warn
      - backup_count
      - last_backup_datetime
    """
    ...

def should_run_auto_backup(backup_settings): # -> bool:
    """
    True (if applicable) if last backup was old.
    """
    ...

def backup_warning(backup_settings): # -> Literal['', 'Never backed up.', 'Last backup was more than 1 week ago.']:
    "Get warning if needed."
    ...

def skip_this_backup(): # -> None:
    "Set the last backup time to today."
    ...

def list_backups(outdir) -> List[DatabaseBackupFile]:
    "List all backup files."
    ...

