"""
This type stub file was generated by pyright.
"""

"""
Show books in datatables.
"""
def get_data_tables_list(parameters, is_archived): # -> dict[str, Any]:
    "Book json data for datatables."
    ...

