"""
This type stub file was generated by pyright.
"""

"""
book helper routines.
"""
class BookImportException(Exception):
    """
    Exception to throw on book import error.
    """
    def __init__(self, message=..., cause=...) -> None:
        ...
    


def save_audio_file(audio_file_field_data): # -> str:
    """
    Save the file to disk, return its filename.
    """
    ...

def get_file_content(filefielddata): # -> LiteralString | str:
    """
    Get the content of the file.
    """
    ...

def get_textfile_content(filefielddata): # -> str:
    "Get content as a single string."
    ...

def get_epub_content(epub_file_field_data): # -> LiteralString:
    """
    Get the content of the epub as a single string.
    """
    ...

def get_pdf_content_from_form(pdf_file_field_data): # -> str:
    "Get content as a single string from a PDF file using PyPDF2."
    ...

def get_srt_content(srt_file_field_data): # -> LiteralString:
    """
    Get the content of the srt as a single string.
    """
    ...

def get_vtt_content(vtt_file_field_data): # -> LiteralString:
    """
    Get the content of the vtt as a single string.
    """
    ...

def book_from_url(url): # -> Book:
    "Parse the url and load a new Book."
    ...

