"""
This type stub file was generated by pyright.
"""

from lute.db import db

"""
Book statistics.
"""
def get_status_distribution(book): # -> dict:
    """
    Return statuses and count of unique words per status.

    Does a full render of a small number of pages
    to calculate the distribution.
    """
    ...

class BookStats(db.Model):
    "The stats table."
    __tablename__ = ...
    id = ...
    BkID = ...
    distinctterms = ...
    distinctunknowns = ...
    unknownpercent = ...
    status_distribution = ...


def refresh_stats(): # -> None:
    "Refresh stats for all books requiring update."
    ...

def mark_stale(book): # -> None:
    "Mark a book's stats as stale to force refresh."
    ...

