"""
This type stub file was generated by pyright.
"""

"Theming routes."
bp = ...
@bp.route("/current", methods=["GET"])
def current_theme(): # -> Response:
    "Return current css."
    ...

@bp.route("/custom_styles", methods=["GET"])
def custom_styles(): # -> Response:
    """
    Return the custom settings for inclusion in the base.html.
    """
    ...

@bp.route("/next", methods=["POST"])
def set_next_theme(): # -> Response:
    "Go to next theme."
    ...

@bp.route("/toggle_highlight", methods=["POST"])
def toggle_highlight(): # -> Response:
    "Fix the highlight."
    ...

