"""
This type stub file was generated by pyright.
"""

"""
Theming service.

Themes are stored in the css folder.  Current theme is saved in
UserSetting.
"""
default_entry = ...
def list_themes(): # -> list[tuple[str, Any] | tuple[Literal['-'], Literal['(default)']]]:
    """
    List of theme file names and user-readable name.
    """
    ...

def get_current_css(): # -> str:
    """
    Return the current css pointed at by the current_theme user setting.
    """
    ...

def next_theme(): # -> None:
    """
    Move to the next theme in the list of themes.
    """
    ...

