"""
This type stub file was generated by pyright.
"""

from flask_wtf import FlaskForm

"""
Flask-wtf forms.
"""
class TermTagForm(FlaskForm):
    """
    TermTag.
    """
    text = ...
    comment = ...


