"""
This type stub file was generated by pyright.
"""

"""
/termtag routes.
"""
bp = ...
@bp.route("/index", defaults={ "search": None }, methods=["GET"])
@bp.route("/index/<search>", methods=["GET"])
def index(search): # -> str:
    "Index page."
    ...

@bp.route("/datatables", methods=["POST"])
def datatables_active_source(): # -> Response:
    "Datatables data for terms."
    ...

@bp.route("/edit/<int:termtagid>", methods=["GET", "POST"])
def edit(termtagid): # -> Response | str:
    """
    Edit a termtag
    """
    ...

@bp.route("/new", methods=["GET", "POST"])
def new(): # -> Response | str:
    """
    Create a termtag.
    """
    ...

@bp.route("/delete/<int:termtagid>", methods=["POST"])
def delete(termtagid): # -> Response:
    """
    Delete a termtag.
    """
    ...

